// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.0
// source: proto/strsvc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StrClient is the client API for Str service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StrClient interface {
	Count(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountReply, error)
	Uppercase(ctx context.Context, in *UppercaseRequest, opts ...grpc.CallOption) (*UppercaseReply, error)
}

type strClient struct {
	cc grpc.ClientConnInterface
}

func NewStrClient(cc grpc.ClientConnInterface) StrClient {
	return &strClient{cc}
}

func (c *strClient) Count(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountReply, error) {
	out := new(CountReply)
	err := c.cc.Invoke(ctx, "/strsvc.Str/Count", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strClient) Uppercase(ctx context.Context, in *UppercaseRequest, opts ...grpc.CallOption) (*UppercaseReply, error) {
	out := new(UppercaseReply)
	err := c.cc.Invoke(ctx, "/strsvc.Str/Uppercase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrServer is the server API for Str service.
// All implementations must embed UnimplementedStrServer
// for forward compatibility
type StrServer interface {
	Count(context.Context, *CountRequest) (*CountReply, error)
	Uppercase(context.Context, *UppercaseRequest) (*UppercaseReply, error)
	mustEmbedUnimplementedStrServer()
}

// UnimplementedStrServer must be embedded to have forward compatible implementations.
type UnimplementedStrServer struct {
}

func (UnimplementedStrServer) Count(context.Context, *CountRequest) (*CountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Count not implemented")
}
func (UnimplementedStrServer) Uppercase(context.Context, *UppercaseRequest) (*UppercaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Uppercase not implemented")
}
func (UnimplementedStrServer) mustEmbedUnimplementedStrServer() {}

// UnsafeStrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StrServer will
// result in compilation errors.
type UnsafeStrServer interface {
	mustEmbedUnimplementedStrServer()
}

func RegisterStrServer(s grpc.ServiceRegistrar, srv StrServer) {
	s.RegisterService(&Str_ServiceDesc, srv)
}

func _Str_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/strsvc.Str/Count",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrServer).Count(ctx, req.(*CountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Str_Uppercase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UppercaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrServer).Uppercase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/strsvc.Str/Uppercase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrServer).Uppercase(ctx, req.(*UppercaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Str_ServiceDesc is the grpc.ServiceDesc for Str service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Str_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "strsvc.Str",
	HandlerType: (*StrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Count",
			Handler:    _Str_Count_Handler,
		},
		{
			MethodName: "Uppercase",
			Handler:    _Str_Uppercase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/strsvc.proto",
}
