"""
提示词模块
"""

from .prompts import (
    SYSTEM_PROMPT_PRODUCT_IDENTIFICATION,
    SYSTEM_PROMPT_DATA_ANALYSIS,
    INPUT_SCHEMA_PRODUCT_IDENTIFICATION,
    OUTPUT_SCHEMA_PRODUCT_IDENTIFICATION,
    INPUT_SCHEMA_DATA_ANALYSIS,
)
from .reflection_prompts import (
    PRODUCT_VALIDATION_PROMPT,
    DATA_VALIDATION_PROMPT,
    CHART_VALIDATION_PROMPT,
    ANALYSIS_VALIDATION_PROMPT,
    REFLECTION_PROMPT,
    CORRECTION_PROMPT,
    LLM_SELF_REFLECTION,
)

__all__ = [
    # 原有提示词
    "SYSTEM_PROMPT_PRODUCT_IDENTIFICATION",
    "SYSTEM_PROMPT_DATA_ANALYSIS",
    "INPUT_SCHEMA_PRODUCT_IDENTIFICATION",
    "OUTPUT_SCHEMA_PRODUCT_IDENTIFICATION",
    "INPUT_SCHEMA_DATA_ANALYSIS",
    # 反思提示词
    "PRODUCT_VALIDATION_PROMPT",
    "DATA_VALIDATION_PROMPT",
    "CHART_VALIDATION_PROMPT",
    "ANALYSIS_VALIDATION_PROMPT",
    "REFLECTION_PROMPT",
    "CORRECTION_PROMPT",
    "LLM_SELF_REFLECTION",
]
